### ISSUE TITLE
Closing an `AsynchronousTlsChannel` concurrently with an `AsynchronousTlsChannelGroup` registering it sometimes causes termination of the `selectorThread`

### ISSUE THREAD

**Issue by stIncMale** [marianobarrios/tls-channel#34] opened 2021-12-08 00:29 UTC
The method [`AsynchronousTlsChannelGroup.registerSocket`](https://github.com/marianobarrios/tls-channel/blob/4c35a49f6a2954ff52b8510e59c3cc1c4c49dbe2/src/main/java/tlschannel/async/AsynchronousTlsChannelGroup.java#L212) initiates an asynchronous activity and returns. This method is [called from the constructor of `AsynchronousTlsChannel`](https://github.com/marianobarrios/tls-channel/blob/4c35a49f6a2954ff52b8510e59c3cc1c4c49dbe2/src/main/java/tlschannel/async/AsynchronousTlsChannel.java#L66), which does not wait on `RegisteredSocket.registered` until the registration is complete (I am not suggesting that it should). As a result, it is possible to create an `AsynchronousTlsChannel` and call its `close` method concurrently with `AsynchronousTlsChannelGroup` [registering](https://github.com/marianobarrios/tls-channel/blob/4c35a49f6a2954ff52b8510e59c3cc1c4c49dbe2/src/main/java/tlschannel/async/AsynchronousTlsChannelGroup.java#L590) its `registeredSocket.socketChannel`. This scenario does not abuse the API, but it allows executions where the following happens:

- [`AsynchronousTlsChannelGroup.registerPendingSockets`](https://github.com/marianobarrios/tls-channel/blob/4c35a49f6a2954ff52b8510e59c3cc1c4c49dbe2/src/main/java/tlschannel/async/AsynchronousTlsChannelGroup.java#L587) observes a closed `SocketChannel` polled from `pendingRegistrations`.
- `SocketChannel.register` called on a closed `SocketChannel` throws a `ClosedChannelException`.
- The method [`AsynchronousTlsChannelGroup.loop`](https://github.com/marianobarrios/tls-channel/blob/4c35a49f6a2954ff52b8510e59c3cc1c4c49dbe2/src/main/java/tlschannel/async/AsynchronousTlsChannelGroup.java#L369) exits its `while` loop as a result of the `ClosedChannelException` thrown from `registerPendingSockets`.
- The [`AsynchronousTlsChannelGroup.selectorThread`](https://github.com/marianobarrios/tls-channel/blob/4c35a49f6a2954ff52b8510e59c3cc1c4c49dbe2/src/main/java/tlschannel/async/AsynchronousTlsChannelGroup.java#L150-L151) terminates, rendering the `AsynchronousTlsChannelGroup` broken.

We [shade tls-channel in mongo-java-driver](https://github.com/mongodb/mongo-java-driver/tree/master/driver-core/src/main/com/mongodb/internal/connection/tlschannel), and received a [report](https://jira.mongodb.org/browse/JAVA-4417) which boils down to the bug I described. I can imagine two straightforward approaches on fixing it:

1. Wait on `RegisteredSocket.registered` in `AsynchronousTlsChannel.close` before closing `tlsChannel`, `registeredSocket`. The problem with this approach is that it makes the `AsynchronousTlsChannel.close` method blocking while currently it is not blocking<sup>1</sup>.
2. Catch and ignore `ClosedChannelException` in `AsynchronousTlsChannelGroup.registerPendingSockets` similarly to how it was done in https://github.com/marianobarrios/tls-channel/commit/59b85a7f6ff96cb2d8b9deecb287819fb570a0d9 to fix https://github.com/marianobarrios/tls-channel/issues/18. This approach seems to be fine.

---
<sup>1</sup> My understanding is that [lingering on close](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/StandardSocketOptions.html#SO_LINGER) cannot be configured for a `SocketChannel` in non-blocking mode, and `TlsChannelBuilder.withWaitForCloseConfirmation` has no effect if the underlying channel is non-blocking.

**Comment by marianobarrios** [comment] 2021-12-08 22:36
Thanks for the very detailed report. Reproduced and followed your advice for fixing [here](https://github.com/marianobarrios/tls-channel/pull/35/).

**Comment by marianobarrios** [comment] 2021-12-09 21:19
Fix released in 0.5.1. Please let me know if there is any issue.

**Comment by stIncMale** [comment] 2021-12-10 20:22
Hi @marianobarrios. Thanks for the prompt change. However, the current fix does no call `socket.registered.countDown()` when `ClosedChannelException` happens. My understanding is that as a result, threads that may be waiting in `AsynchronousTlsChannelGroup.startRead`/`startWrite` continue waiting indefinitely. Just calling `socket.registered.countDown()` may also not be enough, because `startRead`/`startWrite` methods does not know that the socket was closed, and `AsynchronousTlsChannelGroup` does not ever complete the read/write operation because it failed to register the socket.

Do you agree with the above assessment?

**Comment by marianobarrios** [comment] 2021-12-12 23:22
I agree. Thanks, this is very insightful. The fix does not seem to be obvious, though. I still think the last release is indeed an improvement, as it prevent a global corruption; what remains seems to be restricted to the "fast closing" socket.

As I said, I don't see a trivial fix. I will share a PR with you for comments as soon as I have it.

**Comment by stIncMale** [comment] 2021-12-14 18:35
If a `CompletableFuture` is used instead of `CountDownLatch` in `RegisteredSocket.registered`, then:

1. The method `AsynchronousTlsChannelGroup.registerPendingSockets` can complete it exceptionally with `ClosedChannelException`.
2. The methods `AsynchronousTlsChannelGroup.startRead`/`startWrite` get `ClosedChannelException` when calling `registered.get()` in `waitForSocketRegistration`, which they can supply to the `onFailure` consumer.

**Comment by marianobarrios** [comment] 2021-12-19 17:22
Hi @stIncMale. I looked at the problem for some time and I think that it is not that easy in the end. The main problem is, I believe, that a socket channel is automatically removed from the selector when closed (see [this](https://stackoverflow.com/questions/9445973/how-to-be-notified-when-a-socketchannel-is-closed), for example). The keys just disappear. This is a problem because we use to registered keys for keeping track of sockets, when to fail operations, etc. I think that the only way is to keep a separate map with the registrations in the channel group and use that for checking closings. This was not my preferred solution at the beginning due to the duplication of state, but the only one I found.

The changes ended up being a little more invasive than I had expected. Would you mind taking a look at this [pull request](https://github.com/marianobarrios/tls-channel/pull/36)? 

Thanks.

**Comment by marianobarrios** [comment] 2021-12-27 04:20
[Released](https://github.com/marianobarrios/tls-channel/releases/tag/0.6.0).

**Closed by marianobarrios** 2021-12-27 04:20 UTC
