### ISSUE TITLE
Spin Loop when underlying channel is closed

### ISSUE THREAD

**Issue by marchof** [marianobarrios/tls-channel#102] opened 2022-10-02 14:20 UTC
Hi @marianobarrios, thanks for providing this very useful library!

I try to use it for a https proxy and encountered the following problem: When the wrapped socket was closed while someone still wants to emit data, the `TlsChannelImpl.wrapAndWrite(ByteBufferSet)` seems to hang in a endless loop. Example stack dump:

```
java.lang.Thread.State: RUNNABLE
at sun.security.ssl.SSLEngineImpl.wrap(java.base@17.0.4.1/SSLEngineImpl.java:146)
at sun.security.ssl.SSLEngineImpl.wrap(java.base@17.0.4.1/SSLEngineImpl.java:123)
at tlschannel.impl.TlsChannelImpl.callEngineWrap(TlsChannelImpl.java:411)
at tlschannel.impl.TlsChannelImpl.wrapLoop(TlsChannelImpl.java:393)
at tlschannel.impl.TlsChannelImpl.wrapAndWrite(TlsChannelImpl.java:383)
at tlschannel.impl.TlsChannelImpl.write(TlsChannelImpl.java:368)
at tlschannel.ServerTlsChannel.write(ServerTlsChannel.java:291)
at tlschannel.ServerTlsChannel.write(ServerTlsChannel.java:296)
at tlschannel.ServerTlsChannel.write(ServerTlsChannel.java:301)
at <my code>
```

The log is filled with

```
Oct 02 07:50:55 ip-172-31-0-148.eu-central-1.compute.internal java[24592]: 2022/10/02 07:50:54.938 TRACE TlsChannelImpl - engine.wrap() result: [status=CLOSED,handshakeStatus=NOT_HANDSHAKING,bytesProduced=0,bytesConsumed=0]; engine status: NOT_HANDSHAKING; srcBuffer: ByteBufferSet[[java.nio.HeapByteBuffer[pos=14 lim=117 cap=32768]]:0:1], outEncrypted: BufferHolder{name='outEncrypted', allocator=tlschannel.TrackingAllocator@2c83ec10, plainData=false, maxSize=17408, opportunisticDispose=true, buffer=java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408], lastSize=17408}
Oct 02 07:50:55 ip-172-31-0-148.eu-central-1.compute.internal java[24592]: 2022/10/02 07:50:54.938 TRACE TlsChannelImpl - engine.wrap() result: [status=CLOSED,handshakeStatus=NOT_HANDSHAKING,bytesProduced=0,bytesConsumed=0]; engine status: NOT_HANDSHAKING; srcBuffer: ByteBufferSet[[java.nio.HeapByteBuffer[pos=14 lim=117 cap=32768]]:0:1], outEncrypted: BufferHolder{name='outEncrypted', allocator=tlschannel.TrackingAllocator@2c83ec10, plainData=false, maxSize=17408, opportunisticDispose=true, buffer=java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408], lastSize=17408}
Oct 02 07:50:55 ip-172-31-0-148.eu-central-1.compute.internal java[24592]: 2022/10/02 07:50:54.938 TRACE TlsChannelImpl - engine.wrap() result: [status=CLOSED,handshakeStatus=NOT_HANDSHAKING,bytesProduced=0,bytesConsumed=0]; engine status: NOT_HANDSHAKING; srcBuffer: ByteBufferSet[[java.nio.HeapByteBuffer[pos=14 lim=117 cap=32768]]:0:1], outEncrypted: BufferHolder{name='outEncrypted', allocator=tlschannel.TrackingAllocator@2c83ec10, plainData=false, maxSize=17408, opportunisticDispose=true, buffer=java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408], lastSize=17408}
```

I assume that `TlsChannelImpl.wrapAndWrite(ByteBufferSet)` should also check the closed state of the channel because in this case the source buffer will never be consumed.

Please let me know if I can add any additional information.

**Comment by marianobarrios** [comment] 2022-10-02 20:47
Thanks @marchof for the report. Unfortunately, I could not reproduce the problem. Closing is inherently racy (it does not take locks, by design), so this is tricky...

Following your logs and the logic of the code, I prepared a fix that should work. Would you be able to test it in your scenario?

Many thanks again.

**Comment by marchof** [comment] 2022-10-03 05:04
Thanks for the quick fix! Sure, I just deployed a version with 0.7.0-SNAPSHOT. It typically takes a couple of days until it hangs. I'll let you know.

**Comment by marchof** [comment] 2022-10-04 05:55
@marianobarrios So far no endless loops any more, also the code change looks reasonable to me.

**Closed** 2022-10-04 07:44 UTC

**Comment by marchof** [comment] 2022-10-04 12:02
Do you publish SNAPSHOT builds or is there a chance to get a release with this change?

**Comment by marianobarrios** [comment] 2022-10-04 12:13
I will release. It's already merged but I wanted to wait a bit more in case you found it again :-). If you are confident, then I don't think I need more.

**Comment by marchof** [comment] 2022-10-04 19:54
Still up and running without endless loop 👍

**Comment by marianobarrios** [comment] 2022-10-04 21:07
Released (but it will take some time to get to Maven Central, I guess). Thanks for your report and testing!

PS: And for [the Java Version Almanac](https://javaalmanac.io/), that I just realized it's yours, and it's awesome.
